name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
    tags: ['v*']
  pull_request:
    branches:
      - "*"
      - "*/*"
      - "**"

jobs:
  build-windows-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: Check CMake version
        run: cmake --version

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install latest conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
          
      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release .. -G "Visual Studio 17 2022" -A Win32
          cmake --build . --config Release
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            build/Release/sscanf.dll
            sscanf2.inc
            LICENSE
            pawn.json
            README.md

  build-linux-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install g++-multilib cmake

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install latest conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Rename and upload artifacts
        run: |
          cd build
          mv ./libsscanf.so ./sscanf.so
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            build/sscanf.so
            sscanf2.inc
            LICENSE
            pawn.json
            README.md

  create-release-packages:
    runs-on: windows-latest
    needs: [build-windows-release, build-linux-release]
    
    steps:
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-build
        
      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-build
        
      - name: Check current directory and list files
        run: |
          echo "Current directory: $pwd"
          echo "=== Files in root ==="
          Get-ChildItem -Path . -Force
          echo "=== Windows-build files ==="
          if (Test-Path "windows-build") { Get-ChildItem -Path "windows-build" -Force }
          echo "=== Linux-build files ==="  
          if (Test-Path "linux-build") { Get-ChildItem -Path "linux-build" -Force }
        
      - name: Move files to workspace root
        run: |
          if (Test-Path "windows-build") {
            Move-Item -Path "windows-build\*" -Destination "." -Force
            Remove-Item -Path "windows-build" -Recurse -Force
          }
          if (Test-Path "linux-build") {
            Move-Item -Path "linux-build\*" -Destination "." -Force
            Remove-Item -Path "linux-build" -Recurse -Force
          }
          
          echo "=== Files after moving ==="
          Get-ChildItem -Path . -Force
        
      - name: Get version
        run: |
          $version = $env:GITHUB_SHA.Substring(0, 7)
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "Version: $version"
            
      - name: Install 7-Zip
        run: choco install 7zip -y
            
      - name: Create Windows package
        run: |
          if (-not (Test-Path "sscanf.dll")) { throw "sscanf.dll not found!" }
          if (-not (Test-Path "sscanf2.inc")) { throw "sscanf2.inc not found!" }
          if (-not (Test-Path "LICENSE")) { throw "LICENSE not found!" }
          
          mkdir windows
          cd windows
          
          copy ..\sscanf.dll amxsscanf.dll
          copy ..\LICENSE LICENSE
          copy ..\pawn.json pawn.json
          copy ..\README.md README.md
          
          mkdir components
          copy ..\sscanf.dll components\sscanf.dll
          
          mkdir plugins
          copy ..\sscanf.dll plugins\sscanf.dll
          
          mkdir pawno
          cd pawno
          mkdir include
          copy ..\..\sscanf2.inc include\sscanf2.inc
          cd ..
          
          mkdir qawno
          cd qawno
          mkdir include
          copy ..\..\sscanf2.inc include\sscanf2.inc
          cd ..
          
          7z a -tzip windows-$env:VERSION.zip *
          cd ..
            
      - name: Create Linux package
        run: |
          if (-not (Test-Path "sscanf.so")) { throw "sscanf.so not found!" }
          
          mkdir linux
          cd linux
          
          copy ..\sscanf.so amxsscanf.so
          copy ..\LICENSE LICENSE
          copy ..\pawn.json pawn.json
          copy ..\README.md README.md
          
          mkdir components
          copy ..\sscanf.so components\sscanf.so
          
          mkdir plugins
          copy ..\sscanf.so plugins\sscanf.so
          
          mkdir pawno
          cd pawno
          mkdir include
          copy ..\..\sscanf2.inc include\sscanf2.inc
          cd ..
          
          mkdir qawno
          cd qawno
          mkdir include
          copy ..\..\sscanf2.inc include\sscanf2.inc
          cd ..
          
          7z a -ttar -so -an * | 7z a -si linux-$env:VERSION.tar.gz
          cd ..
            
      - name: Upload release packages
        uses: actions/upload-artifact@v4
        with:
          name: release-packages
          path: |
            windows-$env:VERSION.zip
            linux-$env:VERSION.tar.gz
