name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
  pull_request:
    branches:
      - "*"
      - "*/*"
      - "**"

jobs:
  build-windows-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: Check CMake version
        run: cmake --version

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install latest conan
        run: |
          python -m pip install --upgrade pip
          pip install conan
          
      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release .. -G "Visual Studio 17 2022" -A Win32
          cmake --build . --config Release
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sscanf-win-release
          path: build/Release/sscanf.dll

  build-linux-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install g++-multilib cmake

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install latest conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Rename libsscanf.so to sscanf.so
        run: |
          cd build
          mv ./libsscanf.so ./sscanf.so

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sscanf-linux-release
          path: build/sscanf.so
